version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"               # Location of package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"               # Location of workflow YAML files
    schedule:
      interval: "weekly"
